### ISSUE TITLE
Custom CustomizableTraceInterceptor reported as InjectablesMustNotBeInstantiated

### ISSUE THREAD

**Issue by pmihalcin** [buschmais/jqa-spring-plugin#22] opened 2018-07-28 16:05 UTC
Given I have:

```
@Configuration
public class LoggingInterceptorConfig {
    @Bean
    public CustomizableTraceInterceptor methodTraceLoggingInterceptor() {
        return new MethodTraceLoggingInterceptor();
    }
}
```

and

```
public class MethodTraceLoggingInterceptor extends CustomizableTraceInterceptor {

    MethodTraceLoggingInterceptor() {
        setEnterMessage("> [ENTRY] " + PLACEHOLDER_METHOD_NAME + "(" + PLACEHOLDER_ARGUMENTS + ")");
        setExitMessage("< [EXIT] " + PLACEHOLDER_METHOD_NAME + " @ " + PLACEHOLDER_INVOCATION_TIME + " ms: " + PLACEHOLDER_RETURN_VALUE);
        setExceptionMessage("< [THROW] " + PLACEHOLDER_METHOD_NAME + " : " + PLACEHOLDER_EXCEPTION);
        setUseDynamicLogger(true);
    }

    @Override
    protected boolean isLogEnabled(Log logger) {
        return logger.isDebugEnabled();
    }

    @Override
    protected void writeToLog(Log logger, String message, Throwable ex) {
        if (ex != null) {
            logger.warn(message, ex);
        } else {
            logger.debug(message);
        }
    }
}
```

it is reported as 
```
[ERROR]   Type=foo.MethodTraceLoggingInterceptor, Method=foo.MethodTraceLoggingInterceptor#void <init>(), Injectable=org.springframework.aop.interceptor.CustomizableTraceInterceptor, LineNumber=8
```
even though I don't have any init method in MethodTraceLoggingInterceptor

**Comment by DirkMahler** [comment] 2018-08-07 09:05
The init method is the constructor, i.e. ` MethodTraceLoggingInterceptor()` which invokes the constructor of the super class (`CustomizableTraceInterceptor `) that is an Injectable.

The rule should be relaxed to allow this case.

**Comment by DirkMahler** [comment] 2020-01-12 18:01
The issue is no longer reproducible, will add a test case and close it.

**Closed as completed** 2020-01-12 18:03 UTC
Labels: type:enhancement, type:question, status:done
